DROP TABLE IF EXISTS assessment;
DROP TABLE IF EXISTS course_enrollment;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "uuid-ossp";